// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/campaign/campaign.proto

package go_micro_service_campaign

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewCampaignRequest struct {
	CampaignName         string   `protobuf:"bytes,1,opt,name=campaignName,proto3" json:"campaignName,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Purpose              string   `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	CampaignTag          string   `protobuf:"bytes,4,opt,name=campaignTag,proto3" json:"campaignTag,omitempty"`
	StartDateTime        string   `protobuf:"bytes,5,opt,name=startDateTime,proto3" json:"startDateTime,omitempty"`
	EndDateTime          string   `protobuf:"bytes,6,opt,name=endDateTime,proto3" json:"endDateTime,omitempty"`
	TemplateId           string   `protobuf:"bytes,7,opt,name=templateId,proto3" json:"templateId,omitempty"`
	CreatedBy            string   `protobuf:"bytes,8,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewCampaignRequest) Reset()         { *m = NewCampaignRequest{} }
func (m *NewCampaignRequest) String() string { return proto.CompactTextString(m) }
func (*NewCampaignRequest) ProtoMessage()    {}
func (*NewCampaignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10ee50d62b9a743a, []int{0}
}

func (m *NewCampaignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewCampaignRequest.Unmarshal(m, b)
}
func (m *NewCampaignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewCampaignRequest.Marshal(b, m, deterministic)
}
func (m *NewCampaignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewCampaignRequest.Merge(m, src)
}
func (m *NewCampaignRequest) XXX_Size() int {
	return xxx_messageInfo_NewCampaignRequest.Size(m)
}
func (m *NewCampaignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewCampaignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewCampaignRequest proto.InternalMessageInfo

func (m *NewCampaignRequest) GetCampaignName() string {
	if m != nil {
		return m.CampaignName
	}
	return ""
}

func (m *NewCampaignRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *NewCampaignRequest) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *NewCampaignRequest) GetCampaignTag() string {
	if m != nil {
		return m.CampaignTag
	}
	return ""
}

func (m *NewCampaignRequest) GetStartDateTime() string {
	if m != nil {
		return m.StartDateTime
	}
	return ""
}

func (m *NewCampaignRequest) GetEndDateTime() string {
	if m != nil {
		return m.EndDateTime
	}
	return ""
}

func (m *NewCampaignRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *NewCampaignRequest) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_10ee50d62b9a743a, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type CampaignByIdRequest struct {
	CampaignId           string   `protobuf:"bytes,1,opt,name=campaignId,proto3" json:"campaignId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignByIdRequest) Reset()         { *m = CampaignByIdRequest{} }
func (m *CampaignByIdRequest) String() string { return proto.CompactTextString(m) }
func (*CampaignByIdRequest) ProtoMessage()    {}
func (*CampaignByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10ee50d62b9a743a, []int{2}
}

func (m *CampaignByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignByIdRequest.Unmarshal(m, b)
}
func (m *CampaignByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignByIdRequest.Marshal(b, m, deterministic)
}
func (m *CampaignByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignByIdRequest.Merge(m, src)
}
func (m *CampaignByIdRequest) XXX_Size() int {
	return xxx_messageInfo_CampaignByIdRequest.Size(m)
}
func (m *CampaignByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignByIdRequest proto.InternalMessageInfo

func (m *CampaignByIdRequest) GetCampaignId() string {
	if m != nil {
		return m.CampaignId
	}
	return ""
}

type CampaignByTagRequest struct {
	CampaignTag          string   `protobuf:"bytes,1,opt,name=campaignTag,proto3" json:"campaignTag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignByTagRequest) Reset()         { *m = CampaignByTagRequest{} }
func (m *CampaignByTagRequest) String() string { return proto.CompactTextString(m) }
func (*CampaignByTagRequest) ProtoMessage()    {}
func (*CampaignByTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10ee50d62b9a743a, []int{3}
}

func (m *CampaignByTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignByTagRequest.Unmarshal(m, b)
}
func (m *CampaignByTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignByTagRequest.Marshal(b, m, deterministic)
}
func (m *CampaignByTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignByTagRequest.Merge(m, src)
}
func (m *CampaignByTagRequest) XXX_Size() int {
	return xxx_messageInfo_CampaignByTagRequest.Size(m)
}
func (m *CampaignByTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignByTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignByTagRequest proto.InternalMessageInfo

func (m *CampaignByTagRequest) GetCampaignTag() string {
	if m != nil {
		return m.CampaignTag
	}
	return ""
}

type CampaignResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignName         string   `protobuf:"bytes,2,opt,name=campaignName,proto3" json:"campaignName,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Purpose              string   `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	CampaignTag          string   `protobuf:"bytes,5,opt,name=campaignTag,proto3" json:"campaignTag,omitempty"`
	StartDateTime        string   `protobuf:"bytes,6,opt,name=startDateTime,proto3" json:"startDateTime,omitempty"`
	EndDateTime          string   `protobuf:"bytes,7,opt,name=endDateTime,proto3" json:"endDateTime,omitempty"`
	TemplateId           string   `protobuf:"bytes,8,opt,name=templateId,proto3" json:"templateId,omitempty"`
	CreatedBy            string   `protobuf:"bytes,9,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CampaignResponse) Reset()         { *m = CampaignResponse{} }
func (m *CampaignResponse) String() string { return proto.CompactTextString(m) }
func (*CampaignResponse) ProtoMessage()    {}
func (*CampaignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10ee50d62b9a743a, []int{4}
}

func (m *CampaignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CampaignResponse.Unmarshal(m, b)
}
func (m *CampaignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CampaignResponse.Marshal(b, m, deterministic)
}
func (m *CampaignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CampaignResponse.Merge(m, src)
}
func (m *CampaignResponse) XXX_Size() int {
	return xxx_messageInfo_CampaignResponse.Size(m)
}
func (m *CampaignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CampaignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CampaignResponse proto.InternalMessageInfo

func (m *CampaignResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CampaignResponse) GetCampaignName() string {
	if m != nil {
		return m.CampaignName
	}
	return ""
}

func (m *CampaignResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CampaignResponse) GetPurpose() string {
	if m != nil {
		return m.Purpose
	}
	return ""
}

func (m *CampaignResponse) GetCampaignTag() string {
	if m != nil {
		return m.CampaignTag
	}
	return ""
}

func (m *CampaignResponse) GetStartDateTime() string {
	if m != nil {
		return m.StartDateTime
	}
	return ""
}

func (m *CampaignResponse) GetEndDateTime() string {
	if m != nil {
		return m.EndDateTime
	}
	return ""
}

func (m *CampaignResponse) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *CampaignResponse) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func init() {
	proto.RegisterType((*NewCampaignRequest)(nil), "go.micro.service.campaign.NewCampaignRequest")
	proto.RegisterType((*Response)(nil), "go.micro.service.campaign.Response")
	proto.RegisterType((*CampaignByIdRequest)(nil), "go.micro.service.campaign.CampaignByIdRequest")
	proto.RegisterType((*CampaignByTagRequest)(nil), "go.micro.service.campaign.CampaignByTagRequest")
	proto.RegisterType((*CampaignResponse)(nil), "go.micro.service.campaign.CampaignResponse")
}

func init() {
	proto.RegisterFile("proto/campaign/campaign.proto", fileDescriptor_10ee50d62b9a743a)
}

var fileDescriptor_10ee50d62b9a743a = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6a, 0xe3, 0x30,
	0x10, 0xde, 0x38, 0x89, 0xe3, 0xcc, 0xfe, 0xb0, 0x68, 0x97, 0x45, 0x1b, 0x76, 0x43, 0xf0, 0xee,
	0xa1, 0x50, 0xea, 0x40, 0x4b, 0xa1, 0x87, 0x9e, 0x92, 0x42, 0xc8, 0x25, 0x07, 0x93, 0x73, 0x41,
	0xb5, 0x06, 0xa3, 0x52, 0xff, 0xd4, 0x52, 0x5a, 0xf2, 0x2e, 0x7d, 0x82, 0x3e, 0x43, 0x1f, 0xae,
	0x44, 0xb1, 0x62, 0x27, 0x69, 0x1d, 0xf7, 0xe6, 0xf9, 0xe6, 0x9b, 0x19, 0xeb, 0xfb, 0x46, 0x82,
	0xbf, 0x69, 0x96, 0xa8, 0x64, 0x18, 0xb0, 0x28, 0x65, 0x22, 0x8c, 0x37, 0x1f, 0x9e, 0xc6, 0xc9,
	0xef, 0x30, 0xf1, 0x22, 0x11, 0x64, 0x89, 0x27, 0x31, 0x7b, 0x10, 0x01, 0x7a, 0x86, 0xe0, 0x3e,
	0x59, 0x40, 0x66, 0xf8, 0x38, 0xce, 0x63, 0x1f, 0xef, 0x17, 0x28, 0x15, 0x71, 0xe1, 0x8b, 0xa1,
	0xcc, 0x58, 0x84, 0xb4, 0x31, 0x68, 0x1c, 0x75, 0xfd, 0x2d, 0x8c, 0x0c, 0xe0, 0x33, 0x47, 0x19,
	0x64, 0x22, 0x55, 0x22, 0x89, 0xa9, 0xa5, 0x29, 0x65, 0x88, 0x50, 0xe8, 0xa4, 0x8b, 0x2c, 0x4d,
	0x24, 0xd2, 0xa6, 0xce, 0x9a, 0x70, 0x55, 0x6b, 0x7a, 0xcd, 0x59, 0x48, 0x5b, 0xeb, 0xda, 0x12,
	0x44, 0xfe, 0xc3, 0x57, 0xa9, 0x58, 0xa6, 0xae, 0x98, 0xc2, 0xb9, 0x88, 0x90, 0xb6, 0x35, 0x67,
	0x1b, 0x5c, 0xf5, 0xc1, 0x98, 0x6f, 0x38, 0xf6, 0xba, 0x4f, 0x09, 0x22, 0x7d, 0x00, 0x85, 0x51,
	0x7a, 0xc7, 0x14, 0x4e, 0x39, 0xed, 0x68, 0x42, 0x09, 0x21, 0x7f, 0xa0, 0x1b, 0x64, 0xc8, 0x14,
	0xf2, 0xd1, 0x92, 0x3a, 0x3a, 0x5d, 0x00, 0xee, 0x25, 0x38, 0x3e, 0xca, 0x34, 0x89, 0x25, 0xae,
	0x4e, 0x13, 0xa1, 0x94, 0x2c, 0x34, 0x72, 0x98, 0x90, 0xfc, 0x02, 0x5b, 0x2a, 0xa6, 0x16, 0x52,
	0x8b, 0xe0, 0xf8, 0x79, 0xe4, 0x9e, 0xc3, 0x0f, 0x23, 0xec, 0x68, 0x39, 0xe5, 0x46, 0xdc, 0x3e,
	0x80, 0x39, 0xe9, 0x94, 0xe7, 0xbd, 0x4a, 0x88, 0x7b, 0x01, 0x3f, 0x8b, 0xb2, 0x39, 0x0b, 0x4d,
	0xdd, 0x8e, 0x68, 0x8d, 0x3d, 0xd1, 0xdc, 0x67, 0x0b, 0xbe, 0x17, 0x56, 0xe6, 0xff, 0xfd, 0x0d,
	0x2c, 0x61, 0xc6, 0x58, 0x82, 0xef, 0x79, 0x6b, 0x1d, 0xf6, 0xb6, 0x59, 0xe9, 0x6d, 0xab, 0xd2,
	0xdb, 0x76, 0x0d, 0x6f, 0xed, 0x1a, 0xde, 0x76, 0x0e, 0x79, 0xeb, 0x54, 0x7b, 0xdb, 0xdd, 0xf1,
	0xf6, 0xf4, 0xc5, 0x02, 0xc7, 0x88, 0x45, 0xae, 0xc1, 0x1e, 0xeb, 0x0c, 0x39, 0xf1, 0xde, 0xbd,
	0x2d, 0xde, 0xfe, 0x4d, 0xe9, 0xfd, 0xab, 0xa0, 0x1b, 0x0b, 0xdc, 0x4f, 0x84, 0x43, 0x73, 0x82,
	0x8a, 0x78, 0x15, 0xec, 0x37, 0x56, 0xa5, 0x77, 0x5c, 0x83, 0x5f, 0x9a, 0x72, 0x0b, 0xce, 0x04,
	0x95, 0x5e, 0x1a, 0x32, 0xac, 0x35, 0xaa, 0x58, 0xaf, 0x0f, 0xce, 0xba, 0xb1, 0xf5, 0xdb, 0x72,
	0xf6, 0x1a, 0x00, 0x00, 0xff, 0xff, 0x98, 0x11, 0xc0, 0xb6, 0x7c, 0x04, 0x00, 0x00,
}
